tmux new -d -s brca1 
tmux send-keys -t brca1 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s BRCA_1408-06                       -a /diskmnt/Projects/HTAN_analysis_2/Cellranger-atac/BR_HTAN/Cellranger_atac_v.2.0/1408-06                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s brca2 
tmux send-keys -t brca2 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s BRCA_TWCE-HT029B1-XBa1                       -a /diskmnt/Projects/HTAN_analysis_2/Cellranger-atac/BR_HTAN/Cellranger_atac_v.2.0/TWCE-HT029B1-XBa1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s brca3 
tmux send-keys -t brca3 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s BRCA_TWCE-HT035B-XBa1                       -a /diskmnt/Projects/HTAN_analysis_2/Cellranger-atac/BR_HTAN/Cellranger_atac_v.2.0/TWCE-HT035B-XBa1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s brca4 
tmux send-keys -t brca4 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s BRCA_TWCE-HT088B1-S1H1A2K2Y2N1-ATAC                       -a /diskmnt/Projects/HTAN_analysis_2/Cellranger-atac/BR_HTAN/Cellranger_atac_v.2.0/TWCE-HT088B1-S1H1A2K2Y2N1-ATAC                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s brca5 
tmux send-keys -t brca5 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s BRCA_TWCE-HT088B1-S1H2A2Y1N1-ATAC                       -a /diskmnt/Projects/HTAN_analysis_2/Cellranger-atac/BR_HTAN/Cellranger_atac_v.2.0/TWCE-HT088B1-S1H2A2Y1N1-ATAC                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s brca6 
tmux send-keys -t brca6 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s BRCA_TWCE-HT128B1-XBa2_1-HT128B1-XBa2                       -a /diskmnt/Projects/HTAN_analysis_2/Cellranger-atac/BR_HTAN/Cellranger_atac_v.2.0/TWCE-HT128B1-XBa2_1-HT128B1-XBa2                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s brca7 
tmux send-keys -t brca7 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s BRCA_TWCE-HT137B1-XBa1                       -a /diskmnt/Projects/HTAN_analysis_2/Cellranger-atac/BR_HTAN/Cellranger_atac_v.2.0/TWCE-HT137B1-XBa1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s brca8 
tmux send-keys -t brca8 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s BRCA_TWCE-HT141B1-XBa1                       -a /diskmnt/Projects/HTAN_analysis_2/Cellranger-atac/BR_HTAN/Cellranger_atac_v.2.0/TWCE-HT141B1-XBa1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s brca9 
tmux send-keys -t brca9 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s BRCA_TWCE-HT163B1-S1H6A3-XBa1                       -a /diskmnt/Projects/HTAN_analysis_2/Cellranger-atac/BR_HTAN/Cellranger_atac_v.2.0/TWCE-HT163B1-S1H6A3-XBa1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s brca10 
tmux send-keys -t brca10 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s BRCA_TWCE-HT206B1-XBa1_1-HT206B1-XBa1                       -a /diskmnt/Projects/HTAN_analysis_2/Cellranger-atac/BR_HTAN/Cellranger_atac_v.2.0/TWCE-HT206B1-XBa1_1-HT206B1-XBa1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s brca11 
tmux send-keys -t brca11 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s BRCA_TWCE-HT214B1-XBa1                       -a /diskmnt/Projects/HTAN_analysis_2/Cellranger-atac/BR_HTAN/Cellranger_atac_v.2.0/TWCE-HT214B1-XBa1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s brca12 
tmux send-keys -t brca12 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s BRCA_TWCE-HT217B1-XBa1                       -a /diskmnt/Projects/HTAN_analysis_2/Cellranger-atac/BR_HTAN/Cellranger_atac_v.2.0/TWCE-HT217B1-XBa1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc13 
tmux send-keys -t ccrcc13 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0000870003                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0000870003                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc14 
tmux send-keys -t ccrcc14 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0000880001                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0000880001                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc15 
tmux send-keys -t ccrcc15 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0000890002                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0000890002                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc16 
tmux send-keys -t ccrcc16 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0001180011                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0001180011                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc17 
tmux send-keys -t ccrcc17 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0001220012                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0001220012                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc18 
tmux send-keys -t ccrcc18 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0001260013                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0001260013                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc19 
tmux send-keys -t ccrcc19 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0001270002                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0001270002                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc20 
tmux send-keys -t ccrcc20 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0001500003                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0001500003                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc21 
tmux send-keys -t ccrcc21 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0001540013                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0001540013                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc22 
tmux send-keys -t ccrcc22 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0010100001                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0010100001                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc23 
tmux send-keys -t ccrcc23 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0010160004                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0010160004                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc24 
tmux send-keys -t ccrcc24 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0012280004                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0012280004                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc25 
tmux send-keys -t ccrcc25 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0012550012                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0012550012                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc26 
tmux send-keys -t ccrcc26 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0014450005                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0014450005                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc27 
tmux send-keys -t ccrcc27 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0014470002                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0014470002                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc28 
tmux send-keys -t ccrcc28 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0019130004                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0019130004                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc29 
tmux send-keys -t ccrcc29 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0023690004                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0023690004                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc30 
tmux send-keys -t ccrcc30 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0025110004                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0025110004                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc31 
tmux send-keys -t ccrcc31 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0025880013                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0025880013                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc32 
tmux send-keys -t ccrcc32 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0063630004                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0063630004                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc33 
tmux send-keys -t ccrcc33 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0065690004                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0065690004                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc34 
tmux send-keys -t ccrcc34 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0075130004                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0075130004                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc35 
tmux send-keys -t ccrcc35 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0075170013                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0075170013                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc36 
tmux send-keys -t ccrcc36 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0075720013                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0075720013                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc37 
tmux send-keys -t ccrcc37 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0078510004                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0078510004                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc38 
tmux send-keys -t ccrcc38 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0079410004                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0079410004                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc39 
tmux send-keys -t ccrcc39 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0086350004                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0086350004                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ccrcc40 
tmux send-keys -t ccrcc40 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s ccRCC_CPT0086820004                       -a /diskmnt/Projects/cptac_scratch/ccRCC/cellranger-atac/ccRCC_CPT0086820004                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s cesc41 
tmux send-keys -t cesc41 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s CESC_TWDD-CE321C1-S1Y1-XBa1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/CESC/cellranger-atac-v.2/CESC_TWDD-CE321C1-S1Y1-XBa1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s cesc42 
tmux send-keys -t cesc42 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s CESC_TWDD-CE327-CE327N1_1Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/CESC/cellranger-atac-v.2/CESC_TWDD-CE327-CE327N1_1Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s cesc43 
tmux send-keys -t cesc43 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s CESC_TWDD-CE334E1-N1Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/CESC/cellranger-atac-v.2/CESC_TWDD-CE334E1-N1Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s cesc44 
tmux send-keys -t cesc44 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s CESC_TWDD-CE507-CE507N1_1Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/CESC/cellranger-atac-v.2/CESC_TWDD-CE507-CE507N1_1Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s cesc45 
tmux send-keys -t cesc45 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s CESC_TWDD-CE598-CE598N1_1Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/CESC/cellranger-atac-v.2/CESC_TWDD-CE598-CE598N1_1Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s crc46 
tmux send-keys -t crc46 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s CRC_CM556C1-T1Y2_2N1Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/CRC/cellranger-atac-v.2/CRC_CM556C1-T1Y2_2N1Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s crc47 
tmux send-keys -t crc47 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s CRC_CM618C1-T1Y2_2N1Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/CRC/cellranger-atac-v.2/CRC_CM618C1-T1Y2_2N1Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s crc48 
tmux send-keys -t crc48 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s CRC_CM618C2-S1Y2_2N1Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/CRC/cellranger-atac-v.2/CRC_CM618C2-S1Y2_2N1Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s crc49 
tmux send-keys -t crc49 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s CRC_CM663C1-S1Y1N1Bma1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/CRC/cellranger-atac-v.2/CRC_CM663C1-S1Y1N1Bma1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm50 
tmux send-keys -t gbm50 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3L-02705_CPT0189650015_2020-06-16                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3L-02705_CPT0189650015_2020-06-16                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm51 
tmux send-keys -t gbm51 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3L-03405_CPT0224600013_2021-02-01                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3L-03405_CPT0224600013_2021-02-01                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm52 
tmux send-keys -t gbm52 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3L-03968_CPT0228220004_2021-01-29                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3L-03968_CPT0228220004_2021-01-29                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm53 
tmux send-keys -t gbm53 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-00662_CPT0087680014_2021-01-25                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-00662_CPT0087680014_2021-01-25                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm54 
tmux send-keys -t gbm54 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-00663_CPT0087730014_2020-10-15                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-00663_CPT0087730014_2020-10-15                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm55 
tmux send-keys -t gbm55 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-01334_CPT0125220004_2020-06-18                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-01334_CPT0125220004_2020-06-18                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm56 
tmux send-keys -t gbm56 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-01518_CPT0167640014_2020-07-22                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-01518_CPT0167640014_2020-07-22                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm57 
tmux send-keys -t gbm57 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-01798_CPT0167750015_2021-02-02                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-01798_CPT0167750015_2021-02-02                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm58 
tmux send-keys -t gbm58 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-01814_CPT0167860015_2021-02-02                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-01814_CPT0167860015_2021-02-02                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm59 
tmux send-keys -t gbm59 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-01816_CPT0168080014_2020-06-08                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-01816_CPT0168080014_2020-06-08                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm60 
tmux send-keys -t gbm60 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-01818_CPT0168270014_2020-07-23                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-01818_CPT0168270014_2020-07-23                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm61 
tmux send-keys -t gbm61 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-02181_CPT0168380014_2021-02-01                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-02181_CPT0168380014_2021-02-01                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm62 
tmux send-keys -t gbm62 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-02186_CPT0168720014_2020-07-27                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-02186_CPT0168720014_2020-07-27                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm63 
tmux send-keys -t gbm63 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-02188_CPT0168830014_2020-06-03                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-02188_CPT0168830014_2020-06-03                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm64 
tmux send-keys -t gbm64 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-02769_CPT0205570014_2020-06-15                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-02769_CPT0205570014_2020-06-15                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm65 
tmux send-keys -t gbm65 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-02783_CPT0205890014_2021-01-25                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-02783_CPT0205890014_2021-01-25                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm66 
tmux send-keys -t gbm66 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-02784_CPT0206000015_2020-06-10                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-02784_CPT0206000015_2020-06-10                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm67 
tmux send-keys -t gbm67 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_C3N-03186_CPT0206880004_2020-06-22                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_C3N-03186_CPT0206880004_2020-06-22                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm68 
tmux send-keys -t gbm68 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_PT-NPJ7_CPT0204370002_2020-10-19                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_PT-NPJ7_CPT0204370002_2020-10-19                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s gbm69 
tmux send-keys -t gbm69 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s GBM_PT-R55F_CPT0204390001_2020-10-21                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/GBM/cellranger-atac-v.2/GBM_PT-R55F_CPT0204390001_2020-10-21                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm70 
tmux send-keys -t mm70 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-BM2-Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-BM2-Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm71 
tmux send-keys -t mm71 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-BM4-Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-BM4-Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm72 
tmux send-keys -t mm72 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-BM5-Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-BM5-Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm73 
tmux send-keys -t mm73 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-MMY18273-N1B1ATAC                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-MMY18273-N1B1ATAC                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm74 
tmux send-keys -t mm74 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-MMY21940-N1B1ATAC                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-MMY21940-N1B1ATAC                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm75 
tmux send-keys -t mm75 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-MMY22933-N1B1ATAC                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-MMY22933-N1B1ATAC                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm76 
tmux send-keys -t mm76 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-MMY34339-N1B1ATAC                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-MMY34339-N1B1ATAC                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm77 
tmux send-keys -t mm77 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-MMY34600-N1B1ATAC                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-MMY34600-N1B1ATAC                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm78 
tmux send-keys -t mm78 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-MMY70893-N1B1ATAC                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-MMY70893-N1B1ATAC                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm79 
tmux send-keys -t mm79 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-MMY80649-N1B1ATAC                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-MMY80649-N1B1ATAC                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm80 
tmux send-keys -t mm80 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-WU044-Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-WU044-Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm81 
tmux send-keys -t mm81 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-WU082-Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-WU082-Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm82 
tmux send-keys -t mm82 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-WU090-Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-WU090-Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s mm83 
tmux send-keys -t mm83 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s MM_H_YX-WU093-Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/MM/cellranger-atac-v.2/MM_H_YX-WU093-Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ov84 
tmux send-keys -t ov84 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s OV_TWIT-VF029V1-S1Y2_2N1Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/OV/cellranger-atac-v.2/OV_TWIT-VF029V1-S1Y2_2N1Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ov85 
tmux send-keys -t ov85 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s OV_TWIT-VF031V1-TM1Y2_2N1Ba1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/OV/cellranger-atac-v.2/OV_TWIT-VF031V1-TM1Y2_2N1Ba1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s pdac86 
tmux send-keys -t pdac86 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s PDAC_TWCE-HT-018-P-Slice2_ATAC-lib1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/PDAC/cellranger-atac-v.2/PDAC_TWCE-HT-018-P-Slice2_ATAC-lib1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s pdac87 
tmux send-keys -t pdac87 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s PDAC_TWCE-HT-020-P-PunchA2_ATAC-lib1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/PDAC/cellranger-atac-v.2/PDAC_TWCE-HT-020-P-PunchA2_ATAC-lib1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s pdac88 
tmux send-keys -t pdac88 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s PDAC_TWCE-HT-022-P-PunchA1_ATAC-lib1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/PDAC/cellranger-atac-v.2/PDAC_TWCE-HT-022-P-PunchA1_ATAC-lib1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s pkd89 
tmux send-keys -t pkd89 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s PKD_TWAW-K1900070_1FB-XBa1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/PKD/cellranger-atac-v.2/PKD_TWAW-K1900070_1FB-XBa1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ucec90 
tmux send-keys -t ucec90 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s UCEC_TWHG-CPT4096DU-XBa1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/UCEC/cellranger-atac-v.2/UCEC_TWHG-CPT4096DU-XBa1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ucec91 
tmux send-keys -t ucec91 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s UCEC_TWHG-CPT4096DU-XBa2_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/UCEC/cellranger-atac-v.2/UCEC_TWHG-CPT4096DU-XBa2_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ucec92 
tmux send-keys -t ucec92 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s UCEC_TWHG-CPT4427DU-XBa1_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/UCEC/cellranger-atac-v.2/UCEC_TWHG-CPT4427DU-XBa1_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
tmux new -d -s ucec93 
tmux send-keys -t ucec93 'conda activate signac && Rscript /diskmnt/Projects/Users/allakarpova/scripts/snATAC_my/atac_pipeline_v4.0.R                       -s UCEC_TWHG-CPT4427DU-XBa2_1                       -a /diskmnt/Projects/snATAC_primary/01_processed_bam_cellranger/UCEC/cellranger-atac-v.2/UCEC_TWHG-CPT4427DU-XBa2_1                       -o /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v4.0                       --prf_min 1000 --pct_min 15 --ns_max 5 --pc_first 2                       --chrom_size /diskmnt/Projects/snATAC_primary/02_atac_rds_signca/v3.0/hg38.chrom.sizes.txt                       --macs2_path /diskmnt/Projects/Users/allakarpova/Tools/anaconda3/envs/signac/bin/macs2' ENTER
